name: InvestmentCalendar
options:
  minimumXcodeGenVersion: 2.40.0
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    SWIFT_VERSION: "5.0"
targets:
  InvestmentCalendar:
    type: application
    platform: iOS
    sources:
      - InvestmentCalendarApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.andyyu.InvestmentCalendar
        DEVELOPMENT_TEAM: 8N677K2SG2
        CODE_SIGN_STYLE: Automatic
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        INFOPLIST_FILE: InvestmentCalendarApp/Info.plist
        GENERATE_INFOPLIST_FILE: NO
        TARGETED_DEVICE_FAMILY: "1"
        SUPPORTED_PLATFORMS: "iphoneos iphonesimulator"
        SUPPORTS_MACCATALYST: NO
        SUPPORTS_MAC_DESIGNED_FOR_IPHONE_IPAD: NO
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
